tpch:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: TRANSFORMER
      warehouse: TRANSFORMING
      database: DOUG_DEMO_V2
      schema: TPCH
