name: pre-commit-dbt
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pre_commit_dbt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dpguthrie/action-pre-commit@0.0.4
      with:
        files: ${{ steps.file_changes.outputs.files }}
