name: Testing

on:
  workflow_dispatch:
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous workflow timestamp
        uses: dpguthrie/last-workflow-completed-at@v0.1.1
        id: last_completed_at
